"""
DCCP world-model rollout assembly

本文件负责将 nominal imagined rollout、decision-sensitive state mining、
counterfactual branch construction 和 high-margin preference construction 串联起来

该模块输出固定字段的 pref_* batch
这些字段用于后续计算 DCCP 的 local DPO-style preference loss
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Callable, Optional

import numpy as np

from verl.utils.dccp_branching import (
    DCCPActionCandidate,
    DCCPBranchingConfig,
    DCCPScoredBranchSet,
    build_and_score_counterfactual_branches,
    build_candidate_action_set,
    validate_candidate_set,
)
from verl.utils.dccp_mining import (
    DCCPMiningConfig,
    DCCPMiningResult,
    mine_decision_sensitive_states,
    summarize_mining_result,
)
from verl.utils.dccp_preferences import (
    DCCPPreferenceConfig,
    DCCPPreferencePair,
    build_high_margin_preferences,
    flatten_preference_results,
    pack_preference_batch_by_rollout,
    summarize_preference_pairs,
)
from verl.utils.dccp_schema import PREF_KEYS
from verl.utils.dccp_scorer import DCCPScorer


@dataclass
class DCCPRolloutConfig:
    """Hyperparameters for DCCP rollout-side preference construction"""

    mining: DCCPMiningConfig = field(default_factory=DCCPMiningConfig)
    branching: DCCPBranchingConfig = field(default_factory=DCCPBranchingConfig)
    preference: DCCPPreferenceConfig = field(default_factory=DCCPPreferenceConfig)

    max_pairs_per_rollout: int = 4
    max_pairs_per_batch: int = 64
    require_completion_score: bool = True


@dataclass
class DCCPNominalStep:
    """One decision step in a nominal imagined rollout"""

    state_index: int

    context: dict[str, Any]
    state_context: Any

    response_tokens: Any
    action_for_world_model: Any
    response_mask: Any

    action_token_logits: Optional[Any] = None
    entropy_score: Optional[float] = None

    generation_logprob: Optional[float] = None
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class DCCPNominalRollout:
    """One nominal imagined rollout generated by old policy and world model"""

    rollout_id: str
    instruction: str
    video: Any
    steps: list[DCCPNominalStep]
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class DCCPRolloutPreferenceResult:
    """DCCP preference construction result for one nominal imagined rollout"""

    rollout_id: str
    completion_score: Optional[int]
    mining_result: DCCPMiningResult
    scored_branch_sets: list[DCCPScoredBranchSet]
    preference_pairs: list[DCCPPreferencePair]
    metrics: dict[str, float]


AlternativeActionSamplerFn = Callable[
    [DCCPNominalRollout, DCCPNominalStep, int],
    tuple[list[Any], list[Any], Optional[list[Optional[float]]], Optional[list[dict[str, Any]]]],
]

CounterfactualBranchRolloutFn = Callable[
    [Any, DCCPActionCandidate, int, Optional[dict[str, Any]]],
    Any,
]

ReferenceGapFn = Callable[
    [dict[str, Any], DCCPActionCandidate, DCCPActionCandidate],
    float,
]


class DCCPWorldModelRolloutAssembler:
    """Assemble DCCP preference batches from nominal imagined rollouts"""

    def __init__(
        self,
        scorer: DCCPScorer,
        config: DCCPRolloutConfig,
        sample_alternative_actions_fn: AlternativeActionSamplerFn,
        rollout_counterfactual_branch_fn: CounterfactualBranchRolloutFn,
        reference_gap_fn: ReferenceGapFn,
    ):
        self.scorer = scorer
        self.config = config
        self.sample_alternative_actions_fn = sample_alternative_actions_fn
        self.rollout_counterfactual_branch_fn = rollout_counterfactual_branch_fn
        self.reference_gap_fn = reference_gap_fn

    def build_preferences_for_rollout(
        self,
        nominal_rollout: DCCPNominalRollout,
    ) -> DCCPRolloutPreferenceResult:
        """对一条 nominal imagined rollout 构造 DCCP preference pairs"""
        completion_score = None

        if self.config.require_completion_score:
            completion_score = self.scorer.score_trajectory_completion(
                rollout_video=nominal_rollout.video,
                instruction=nominal_rollout.instruction,
                metadata={
                    "rollout_id": nominal_rollout.rollout_id,
                    "score_type": "trajectory_completion",
                    **dict(nominal_rollout.metadata),
                },
            )

        entropy_scores = self._collect_entropy_scores(nominal_rollout)

        decision_indices = [
            int(step.state_index)
            for step in nominal_rollout.steps
        ]

        mining_result = mine_decision_sensitive_states(
            rollout_video=nominal_rollout.video,
            instruction=nominal_rollout.instruction,
            scorer=self.scorer,
            entropy_scores=entropy_scores,
            config=self.config.mining,
            decision_indices=decision_indices,
            metadata={
                "rollout_id": nominal_rollout.rollout_id,
                **dict(nominal_rollout.metadata),
            },
        )

        scored_branch_sets: list[DCCPScoredBranchSet] = []
        preference_build_results = []

        step_by_index = {int(step.state_index): step for step in nominal_rollout.steps}

        for selected_state in mining_result.selected_states:
            state_index = int(selected_state.index)

            if state_index not in step_by_index:
                continue

            nominal_step = step_by_index[state_index]

            alternative_responses, alternative_actions, alternative_logprobs, alternative_metadata = (
                self.sample_alternative_actions_fn(
                    nominal_rollout,
                    nominal_step,
                    int(self.config.branching.num_candidates) - 1,
                )
            )

            candidates = build_candidate_action_set(
                nominal_response_tokens=nominal_step.response_tokens,
                nominal_action_for_world_model=nominal_step.action_for_world_model,
                alternative_response_tokens=alternative_responses,
                alternative_actions_for_world_model=alternative_actions,
                config=self.config.branching,
                nominal_generation_logprob=nominal_step.generation_logprob,
                alternative_generation_logprobs=alternative_logprobs,
                nominal_metadata=nominal_step.metadata,
                alternative_metadata=alternative_metadata,
            )

            validate_candidate_set(candidates)

            scored_branch_set = build_and_score_counterfactual_branches(
                state_index=state_index,
                state_context=nominal_step.state_context,
                rollout_video=nominal_rollout.video,
                candidates=candidates,
                rollout_branch_fn=self.rollout_counterfactual_branch_fn,
                instruction=nominal_rollout.instruction,
                scorer=self.scorer,
                config=self.config.branching,
                rollout_metadata={
                    "rollout_id": nominal_rollout.rollout_id,
                    **dict(nominal_rollout.metadata),
                },
                score_metadata={
                    "rollout_id": nominal_rollout.rollout_id,
                    **dict(nominal_rollout.metadata),
                },
            )

            scored_branch_sets.append(scored_branch_set)

            preference_result = build_high_margin_preferences(
                scored_branch_set=scored_branch_set,
                context=nominal_step.context,
                reference_gap_fn=self.reference_gap_fn,
                config=self.config.preference,
                entropy_score=float(selected_state.entropy_score),
                curvature_score=float(selected_state.curvature_score),
                metadata={
                    "rollout_id": nominal_rollout.rollout_id,
                    "state_index": state_index,
                    **dict(nominal_step.metadata),
                },
            )

            preference_build_results.append(preference_result)

        preference_pairs = flatten_preference_results(preference_build_results)

        metrics = {}
        metrics.update(summarize_mining_result(mining_result))
        metrics.update(summarize_preference_pairs(preference_pairs))
        metrics.update(self.scorer.metrics())

        if completion_score is not None:
            metrics["dccp/completion_score"] = float(completion_score)

        return DCCPRolloutPreferenceResult(
            rollout_id=nominal_rollout.rollout_id,
            completion_score=completion_score,
            mining_result=mining_result,
            scored_branch_sets=scored_branch_sets,
            preference_pairs=preference_pairs,
            metrics=metrics,
        )

    def build_preference_batch(
        self,
        nominal_rollouts: list[DCCPNominalRollout],
        padding_context: dict[str, Any],
        padding_response_tokens: Any,
        padding_response_mask: Any,
    ) -> tuple[dict[str, Any], list[DCCPRolloutPreferenceResult], dict[str, float]]:
        """对多条 nominal imagined rollouts 构造按 rollout 分组的 pref_* batch"""
        rollout_results: list[DCCPRolloutPreferenceResult] = []
        preference_pairs_by_rollout: list[list[DCCPPreferencePair]] = []

        for nominal_rollout in nominal_rollouts:
            result = self.build_preferences_for_rollout(nominal_rollout)
            rollout_results.append(result)
            preference_pairs_by_rollout.append(result.preference_pairs)

        preference_pairs_by_rollout = _limit_pairs_per_batch(
            preference_pairs_by_rollout=preference_pairs_by_rollout,
            max_pairs_per_batch=int(self.config.max_pairs_per_batch),
        )

        batch = pack_preference_batch_by_rollout(
            preference_pairs_by_rollout=preference_pairs_by_rollout,
            max_pairs_per_rollout=int(self.config.max_pairs_per_rollout),
            padding_context=padding_context,
            padding_response_tokens=padding_response_tokens,
            padding_response_mask=padding_response_mask,
        )

        metrics = self._aggregate_metrics(rollout_results, batch)

        return batch, rollout_results, metrics

    def _collect_entropy_scores(self, nominal_rollout: DCCPNominalRollout) -> np.ndarray:
        """收集每个 decision step 的 action-token entropy"""
        if len(nominal_rollout.steps) == 0:
            return np.zeros((0,), dtype=np.float32)

        max_index = max(int(step.state_index) for step in nominal_rollout.steps)
        entropy_scores = np.zeros((max_index + 1,), dtype=np.float32)

        for step in nominal_rollout.steps:
            if step.entropy_score is None:
                continue
            entropy_scores[int(step.state_index)] = float(step.entropy_score)

        return entropy_scores

    @staticmethod
    def _aggregate_metrics(
        rollout_results: list[DCCPRolloutPreferenceResult],
        batch: dict[str, Any],
    ) -> dict[str, float]:
        """聚合多条 rollout 的 DCCP 日志指标"""
        metrics: dict[str, float] = {}

        if len(rollout_results) == 0:
            metrics["dccp/valid_pairs_rollout"] = 0.0
            metrics["dccp/pref_density"] = 0.0
            return metrics

        metric_buckets: dict[str, list[float]] = {}

        for result in rollout_results:
            for key, value in result.metrics.items():
                metric_buckets.setdefault(key, []).append(float(value))

        for key, values in metric_buckets.items():
            metrics[key] = float(np.mean(np.asarray(values, dtype=np.float32)))

        valid = batch.get(PREF_KEYS.valid)

        if valid is not None:
            valid_array = _to_numpy_bool(valid)
            metrics["dccp/valid_pairs_rollout"] = float(np.sum(valid_array))
            metrics["dccp/pref_density"] = float(np.mean(valid_array)) if valid_array.size > 0 else 0.0

        return metrics


def make_empty_preference_batch(
    batch_size: int,
    max_pairs_per_rollout: int,
    padding_context: dict[str, Any],
    padding_response_tokens: Any,
    padding_response_mask: Any,
) -> dict[str, Any]:
    """构造没有有效 preference pair 时的 padding batch"""
    preference_pairs_by_rollout = [
        []
        for _ in range(int(batch_size))
    ]

    return pack_preference_batch_by_rollout(
        preference_pairs_by_rollout=preference_pairs_by_rollout,
        max_pairs_per_rollout=int(max_pairs_per_rollout),
        padding_context=padding_context,
        padding_response_tokens=padding_response_tokens,
        padding_response_mask=padding_response_mask,
    )


def _to_numpy_bool(value: Any) -> np.ndarray:
    """将 tensor 或 array 转成 bool numpy array"""
    try:
        import torch

        if isinstance(value, torch.Tensor):
            return value.detach().cpu().numpy().astype(bool)
    except ImportError:
        pass

    return np.asarray(value).astype(bool)


def _limit_pairs_per_batch(
    preference_pairs_by_rollout: list[list[DCCPPreferencePair]],
    max_pairs_per_batch: int,
) -> list[list[DCCPPreferencePair]]:
    """Keep the top weighted DCCP pairs across the whole rollout batch."""
    max_pairs_per_batch = int(max_pairs_per_batch)
    if max_pairs_per_batch <= 0:
        return [[] for _ in preference_pairs_by_rollout]

    indexed_pairs = []
    for rollout_idx, rollout_pairs in enumerate(preference_pairs_by_rollout):
        for pair_idx, pair in enumerate(rollout_pairs):
            indexed_pairs.append((rollout_idx, pair_idx, pair))

    if len(indexed_pairs) <= max_pairs_per_batch:
        return preference_pairs_by_rollout

    indexed_pairs = sorted(
        indexed_pairs,
        key=lambda item: (-float(item[2].weight), int(item[2].state_index), int(item[2].candidate_index)),
    )
    kept = {
        (rollout_idx, pair_idx)
        for rollout_idx, pair_idx, _ in indexed_pairs[:max_pairs_per_batch]
    }

    limited: list[list[DCCPPreferencePair]] = []
    for rollout_idx, rollout_pairs in enumerate(preference_pairs_by_rollout):
        limited.append(
            [
                pair
                for pair_idx, pair in enumerate(rollout_pairs)
                if (rollout_idx, pair_idx) in kept
            ]
        )

    return limited
